
stages:
  - build
  - test

golangci-lint v1.50.1:
  stage: test
  image: golangci/golangci-lint:v1.50.1
  script:
    - golangci-lint --version
    - golangci-lint run -v

staticcheck v0.3.3:
  stage: test
  image: golang:1.19
  script:
    - go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
    - staticcheck ./...

compile go 1.19:
  stage: build
  image: golang:1.19
  script:
    - go build -v ./...

unittests:
  stage: test
  image: golang:1.19
  script:
    - go test -race -v ./...

test-report:
  stage: test
  image: golang:1.19
  script:
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

coverage:
  stage: test
  image: golang:1.19
  script:
    - go test ./... -coverprofile=coverage.txt -covermode count
    - go install github.com/boumenot/gocover-cobertura@latest
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
