run:
  timeout: 10m
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo        
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - interfacebloat
    - ineffassign
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - stylecheck
    - staticcheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - usestdlibvars
    - unused
    - varnamelen
    - whitespace
    - wsl

  disable:
    - exhaustruct       # we don't want to fill out every single variable in a struct declaration
    - goerr113          # because our static wrapped errors do not seem to work
    - gofumpt           # requires go 1.18
    - goprintffuncname  # conflicts with our logger
    - paralleltest      # not necessary to do parallel tests for now, might enable later again
    - testpackage       # we don't enforce white box testing
    - wrapcheck         # it's fine to just return some foreign errors
    - golint            # deprecated
    - ifshort           # deprecated
    - interfacer        # deprecated
    - maligned          # deprecated
    - rowserrcheck      # deprecated
    - scopelint         # deprecated
    - sqlclosecheck     # deprecated
    - wastedassign      # deprecated

linters-settings:
  lll:
    line-length: 180
  tagliatelle:
    case:
      rules:
        json: snake   # we expect snake case for keys in JSON config files.

issues:
  exclude-rules:
    - path: _test\.go   # some linter are not suitable in test files.
      linters:
        - dupl
        - funlen        # big table tests could result in long functions
        - lll           # long lines may happen when defining expectet output.
        - maintidx
        - varnamelen    # the name "tt" is obligatory for tests, for example.
    - linters:
        - gosimple
      text: "should omit comparison to bool constant"