---
name: Testing
on:
  push:
  pull_request:
    branches:
      - main
env:
  GO111MODULE: "off"
  GOPATH: "/home/runner/go"

jobs:
  run-qemu:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qqy install \
          linux-image-virtual qemu-system-x86
          sudo chmod 644 /boot/vmlinuz

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Repository symbol link GOPATH
        run: |
          mkdir -p $HOME/go/src/github.com/system-transparency
          ln -s $PWD $HOME/go/src/github.com/system-transparency/stboot

      - name: Get u-root
        run: |
          go get github.com/u-root/u-root

      - name: Build initramfs
        run: |
          mkdir out
          $GOPATH/bin/u-root -o out/initramfs.cpio -uinitcmd stboot github.com/system-transparency/stboot

      - name: Run in QEMU
        run: |
          .github/workflows/scripts/qemu.sh
