---
name: Testing
on:
  push:
  pull_request:
    branches:
      - main
env:
  GO111MODULE: "off"
  GOPATH: "/home/runner/go"

jobs:
  run-qemu-vanilla:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qqy install \
          qemu-system-x86

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Repository symbol link GOPATH
        run: |
          mkdir -p $HOME/go/src/github.com/system-transparency
          ln -s $PWD $HOME/go/src/github.com/system-transparency/stboot

      - name: Get u-root
        run: |
          go get github.com/u-root/u-root

      - name: Build vanilla initramfs
        run: |
          mkdir out
          $GOPATH/bin/u-root -o out/initramfs.cpio -uinitcmd stboot github.com/u-root/u-root/cmds/core/{init,elvish,ls} github.com/system-transparency/stboot

      - name: Run vanilla stboot in QEMU
        run: |
          .github/scripts/qemu.sh vanilla

  run-qemu-complete:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qqy install \
          wget qemu-system-x86

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Repository symbol link GOPATH
        run: |
          mkdir -p $HOME/go/src/github.com/system-transparency
          ln -s $PWD $HOME/go/src/github.com/system-transparency/stboot

      - name: Get u-root
        run: |
          go get github.com/u-root/u-root

      - name: Install stmanager
        run: |
          go install github.com/system-transparency/stboot/tools/stmanager

      - name: Download example OS
        run: |
          mkdir -p out
          cd out
          wget https://github.com/system-transparency/example-os/releases/download/v0.1/ubuntu-focal-amd64.cpio.gz
          wget https://github.com/system-transparency/example-os/releases/download/v0.1/ubuntu-focal-amd64.vmlinuz

      - name: Generate sign keys and create demo ospkg
        run: |
          .github/scripts/ospkg.sh

      - name: Build complete initramfs
        run: |
          .github/scripts/build.sh

      - name: Run stboot in QEMU
        run: |
          .github/scripts/qemu.sh complete
