---
name: Test
on:
  push:
  pull_request:
    branches:
      - main
env:
  UROOT_VERSION: 78ac944
  STMGR_VERSION: 7452628
  GOPATH: "/home/runner/go"

jobs:
  run-qemu-vanilla:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qqy install \
          qemu-system-x86

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Repository symbol link GOPATH
        run: |
          mkdir -p $HOME/go/src/github.com/system-transparency
          ln -s $PWD $HOME/go/src/github.com/system-transparency/stboot

      - name: Get u-root source into GOPATH
        run: |
          go get github.com/u-root/u-root
        env:
          GO111MODULE: "off"

      - name: Install u-root
        run: |
          go install "github.com/u-root/u-root@${{ env.UROOT_VERSION }}"

      - name: Build vanilla initramfs
        run: |
          mkdir out
          $GOPATH/bin/u-root -o out/initramfs.cpio -uinitcmd stboot \
            github.com/u-root/u-root/cmds/core/{init,elvish,ls} \
            github.com/system-transparency/stboot
        env:
          GO111MODULE: "off"

      - name: Run vanilla stboot in QEMU
        run: |
          .github/scripts/qemu.sh vanilla

  run-qemu-complete:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -qqy install \
          wget qemu-system-x86

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add Repository symbol link GOPATH
        run: |
          mkdir -p $HOME/go/src/github.com/system-transparency
          ln -s $PWD $HOME/go/src/github.com/system-transparency/stboot

      - name: Get u-root source into GOPATH
        run: |
          go get github.com/u-root/u-root
        env:
          GO111MODULE: "off"

      - name: Install u-root
        run: |
          go install "github.com/u-root/u-root@${{ env.UROOT_VERSION }}"

      - name: Install stmgr
        run: |
          go install "github.com/system-transparency/stmgr@${{ env.STMGR_VERSION }}"

      - name: Download example OS
        run: |
          mkdir -p out
          cd out
          wget https://github.com/system-transparency/example-os/releases/download/v0.1/ubuntu-focal-amd64.cpio.gz
          wget https://github.com/system-transparency/example-os/releases/download/v0.1/ubuntu-focal-amd64.vmlinuz

      - name: Generate sign keys and create demo ospkg
        run: |
          .github/scripts/ospkg.sh

      - name: Build complete initramfs
        run: |
          .github/scripts/build.sh

      - name: Run stboot in QEMU
        run: |
          .github/scripts/qemu.sh complete
